project_name: kangal

builds:
  - id: binary-build
    main: main.go
    binary: kangal
    ldflags:
      - -s -w -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

dockers:
  - goos: linux
    goarch: amd64
    binaries:
      - kangal
    image_templates:
      - "hellofreshtech/kangal:latest"
      - "hellofreshtech/kangal:{{.Tag}}"
    dockerfile: Dockerfile
    extra_files:
      - openapi.json

release:
  extra_files:
  - glob: kangal/crd.yaml
