site_name: 'Kangal'
site_description: 'Kangal documentation and guides'

plugins:
  - techdocs-core

markdown_extensions:
  - admonition

nav:
  - Home: 'index.md'
  - Troubleshooting guide: 'troubleshooting.md'
  - User flow guide: 'user-flow.md'
  - JMeter load generator:
      - About JMeter load generator: 'jmeter/README.md'
      - Reporting in JMeter: 'jmeter/reporting.md'
      - Writing tests: 'jmeter/writing-tests.md'
  - Locust load generator:
      - About Locust load generator: 'locust/README.md'
  - Ghz load generator:
      - About ghz load generator: 'ghz/README.md'
  - Kangal environment variables: 'env-vars.md'
