{{- $envVars := list "OPEN_API_SERVER_URL" "OPEN_API_SERVER_DESCRIPTION" }}
{{- range $envVar := $envVars }}
  {{- if not (index $.Values.proxy.env $envVar) }}
    {{- fail (printf "required var %s not defined for deployment: proxy %s" $envVar) }}
  {{- end }}
{{- end }}
{{- if index $.Values "openapi-ui" "enabled" }}
{{- $envVars := list "URL" }}
{{- range $envVar := $envVars }}
  {{- if not (index $.Values "openapi-ui" "env" $envVar) }}
    {{- fail (printf "required var %s not defined for deployment: openapi-ui %s" $envVar) }}
  {{- end -}}
{{- end }}
{{- end }}
{{- range $key, $value := .Values -}}
{{- if or (eq $key "proxy") (and (eq $key "openapi-ui") (index $.Values "openapi-ui" "enabled")) (eq $key "controller") }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "<CHARTNAME>.fullname" $ }}-{{ $key }}
  labels:
    app: {{ template "<CHARTNAME>.name" $ }}-{{ $key }}
    chart: {{ template "<CHARTNAME>.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
    version: "{{ if $value.tag }}{{ $value.tag }}{{ else if $.Values.tag }}{{ $.Values.tag }}{{ else }}{{ $.Chart.AppVersion }}{{ end }}"
spec:
  replicas: {{ $value.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "<CHARTNAME>.name" $ }}-{{ $key }}
      release: {{ $.Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "<CHARTNAME>.name" $ }}-{{ $key }}
        release: {{ $.Release.Name }}
        environment: {{ $.Values.environment }}
        version: "{{ if $value.tag }}{{ $value.tag }}{{ else if $.Values.tag }}{{ $.Values.tag }}{{ else }}{{ $.Chart.AppVersion }}{{ end }}"
{{- if or ($.Values.podAnnotations) ($value.podAnnotations) }}
      annotations:
{{- with $.Values.podAnnotations }}
{{ toYaml . | indent 8 }}
{{- end }}
{{- with $value.podAnnotations }}
{{ toYaml . | indent 8 }}
{{- end }}
{{- end }}
    spec:
      {{- if $value.serviceAccountName }}
      serviceAccountName: {{ $value.serviceAccountName }}
      {{- end}}
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      containers:
        - name:  {{ $.Chart.Name }}-{{ $key }}
          {{- if $value.image.tag }}
          image: "{{ $value.image.repository }}:{{ $value.image.tag }}"
          {{- else }}
          image: "{{ $value.image.repository }}:{{ $.Chart.AppVersion }}"
          {{- end }}
          imagePullPolicy: {{ $value.image.pullPolicy }}
          {{- if $value.command }}
          command: {{ $value.command }}
          {{- end }}
          {{- if $value.args }}
          args:
{{ toYaml $value.args | indent 12 }}
          {{- end }}
          env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          {{- if $.Chart.AppVersion }}
          - name: VERSION
            value: "{{ $.Chart.AppVersion }}"
          {{- end }}
          {{- if $value.env }}
          {{- range $envName, $envValue := $value.env }}
          - name: {{ $envName }}
            value: {{ $envValue | quote }}
          {{- end }}
          {{- end }}
          {{- if or ($.Values.configMap) ($.Values.secrets) }}
          envFrom:
          {{- if $.Values.configMap }}
            - configMapRef:
                name: {{ template "<CHARTNAME>.fullname" $ }}
          {{- end }}
          {{- if $.Values.secrets }}
            - secretRef:
                name: {{ template "<CHARTNAME>.fullname" $ }}
          {{- end }}
          {{- end }}
          ports:
          {{- range $label, $port := $value.containerPorts }}
            - name: {{ $label }}
              containerPort: {{ $port }}
              protocol: TCP
          {{- end }}
          {{- with $value.livenessProbe }}
          livenessProbe:
{{ toYaml . | indent 12 }}
          {{- end }}
          {{- with $value.readinessProbe }}
          readinessProbe:
{{ toYaml . | indent 12 }}
          {{- end }}
          resources:
{{ toYaml $value.resources | indent 12 }}
    {{- with $value.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with $value.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with $value.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
{{- end }}
{{- end }}
