{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "<CHARTNAME>.fullname" . }}
  labels:
    app: {{ template "<CHARTNAME>.name" . }}
    chart: {{ template "<CHARTNAME>.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if $.Values.labels }}
{{- with $.Values.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- end }}
data:
  AWS_ACCESS_KEY_ID: {{ .Values.secrets.AWS_ACCESS_KEY_ID | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secrets.AWS_SECRET_ACCESS_KEY | b64enc }}
{{- end }}
