{{- range $key, $value := .Values }}
{{- if or (eq $key "proxy") (eq $key "openapi-ui") (eq $key "controller")}}
{{- if $value.serviceAccount }}
{{- if $value.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "<CHARTNAME>.fullname" $ }}-{{ $key }}
  labels:
    app: {{ template "<CHARTNAME>.name" $ }}-{{ $key }}
    chart: {{ template "<CHARTNAME>.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
{{- if $.Values.labels }}
{{- with $.Values.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- end }}
  {{- if ($value.serviceAccount.annotations) }}
  annotations:
    {{- with $value.serviceAccount.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
